import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, ArrowRight, Banknote, CheckCircle2, ChevronRight, Clock3, Database, GitBranch, HeartPulse, LayoutDashboard, Play, RefreshCw, Server, ShieldCheck, SlidersHorizontal, Zap } from 'lucide-react';
import './style.css';

const API=(import.meta.env.VITE_API_URL||'http://localhost:8080/api').replace(/\/$/,'');
async function api(path:string, init?:RequestInit){const r=await fetch(API+path,init);const text=await r.text();let data:any;try{data=text?JSON.parse(text):{}}catch{data={raw:text}};if(!r.ok)throw new Error(data.error||'Request failed');return data}
const post=(p:string,b?:any)=>api(p,{method:'POST',headers:{'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});
const money=(n:any)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0));

function App(){
 const [page,setPage]=useState('Overview'); const [state,setState]=useState<any>({}); const [payments,setPayments]=useState<any[]>([]); const [events,setEvents]=useState<any[]>([]); const [cons,setCons]=useState<any>({}); const [ledger,setLedger]=useState<any>({}); const [settlement,setSettlement]=useState<any>({}); const [clock,setClock]=useState<any>({}); const [election,setElection]=useState<any>({}); const [toast,setToast]=useState(''); const [busy,setBusy]=useState(false);
 const [amount,setAmount]=useState('45000'); const [method,setMethod]=useState('UPI'); const [processor,setProcessor]=useState(''); const [idem,setIdem]=useState('');
 const refresh=async()=>{try{const [s,p,e,c,l,se]=await Promise.all([api('/state'),api('/payments'),api('/events'),api('/consistency'),api('/ledger/verify'),api('/settlement'),api('/election')]);setState(s);setPayments(p);setEvents(e);setCons(c);setLedger(l);setSettlement(se);setElection(el)}catch(err:any){setToast(err.message+' — start MySQL + Spring Boot')}};
 useEffect(()=>{refresh();const t=setInterval(refresh,2500);return()=>clearInterval(t)},[]);
 const action=async(a:string)=>{setBusy(true);try{await post('/control/'+a);setToast(a.replaceAll('_',' ')+' completed');await refresh()}catch(e:any){setToast(e.message)}finally{setBusy(false)}};
 const createPayment=async()=>{setBusy(true);try{const r=await post('/payments',{orderId:'ORDER-'+Date.now(),customerId:'C-1001',amount:Number(amount.replaceAll(',','')),currency:'INR',method,processor:processor||undefined,idempotencyKey:idem||'IDM-'+Date.now()});setToast(`${r.paymentId} • ${r.status} • ${r.processor} • ${r.node}`);await refresh()}catch(e:any){setToast(e.message)}finally{setBusy(false)}};
 const runDemo=async()=>{setBusy(true);try{await action('RESET');for(const x of [['45000','UPI'],['25000','CARD'],['75000','NETBANKING']]){await post('/payments',{orderId:'DEMO-'+Date.now()+Math.random(),customerId:'C-1001',amount:Number(x[0]),currency:'INR',method:x[1],idempotencyKey:'DEMO-'+x[0]+'-'+Date.now()+Math.random()});}await action('FAIL_PRIMARY');await action('START_ELECTION');await action('PROMOTE_BACKUP');await post('/payments',{orderId:'DEMO-1004',customerId:'C-1001',amount:50000,currency:'INR',method:'UPI',processor:'UPI-Processor',idempotencyKey:'DEMO-PAY-1004-'+Date.now()});await action('RECOVER_PRIMARY');await action('RESTORE_REPLICATION');setToast('Experiment 5 full failover demo completed')}catch(e:any){setToast(e.message)}finally{setBusy(false);refresh()}};
 const success=payments.filter(p=>p.status==='SUCCESS').length; const volume=payments.reduce((a,p)=>a+Number(p.amount||0),0);
 return <div className="shell">
  <aside className="sidebar"><div className="brand"><div className="brandMark">P</div><div><div className="brandName">PAYMESH</div><div className="brandSub">Distributed Payment Fabric</div></div></div>
   <div className="navLabel">CONTROL PLANE</div>{['Overview','Payments','Experiment 5','Nodes & Election','Clock Synchronization','Ledger & Settlement','System Logs'].map(x=><button key={x} className={page===x?'nav active':'nav'} onClick={()=>setPage(x)}>{x==='Overview'?<LayoutDashboard/>:x==='Payments'?<Banknote/>:x==='Experiment 5'?<ShieldCheck/>:x==='Nodes & Election'?<GitBranch/>:x==='Clock Synchronization'?<Clock3/>:x==='Ledger & Settlement'?<Database/>:<Activity/>}<span>{x}</span>{page===x&&<ChevronRight className="navArrow"/>}</button>)}
   <div className="sideBottom"><div className="miniStatus"><span className="dot"></span> Gateway online</div><button className="demoBtn" onClick={runDemo} disabled={busy}><Play size={15}/> Run full viva demo</button></div>
  </aside>
  <main className="main"><header><div><div className="eyebrow">DISTRIBUTED PAYMENT GATEWAY / CONTROL CENTER</div><h1>{page}</h1></div><div className="headerRight"><span className="pill"><span className="pulse"></span> LIVE</span><button className="iconBtn" onClick={refresh}><RefreshCw size={17}/></button></div></header>
   {toast&&<div className="toast"><Zap size={16}/>{toast}<button onClick={()=>setToast('')}>×</button></div>}
   {page==='Overview'&&<Overview state={state} payments={payments} cons={cons} success={success} volume={volume} action={action} busy={busy} setPage={setPage} />}
   {page==='Payments'&&<Payments payments={payments} amount={amount} setAmount={setAmount} method={method} setMethod={setMethod} processor={processor} setProcessor={setProcessor} idem={idem} setIdem={setIdem} create={createPayment}/>} 
   {page==='Experiment 5'&&<Experiment state={state} cons={cons} payments={payments} action={action} busy={busy} runDemo={runDemo}/>} 
   {page==='Nodes & Election'&&<Nodes state={state} action={action} election={election}/>} 
   {page==='Clock Synchronization'&&<Clock clock={clock} setClock={setClock} action={action}/>} 
   {page==='Ledger & Settlement'&&<Ledger ledger={ledger} settlement={settlement} action={action}/>} 
   {page==='System Logs'&&<Logs events={events}/>} 
  </main></div>
}

function Overview({state,payments,cons,success,volume,action,busy,setPage}:any){return <>
 <section className="hero"><div><span className="tag">EXPERIMENT 5 / PRIMARY-BACKUP</span><h2>Resilient payments,<br/><em>observable by design.</em></h2><p>PAYMESH connects payment processing, replication, election, logical clocks and ledger verification into one runnable distributed-systems lab.</p><button onClick={()=>setPage('Experiment 5')} className="primaryBtn">Open fault-tolerance lab <ArrowRight size={16}/></button></div><div className="topology"><NodeCard node="NODE-1" role={state.activePrimary==='NODE-1'?'PRIMARY':'BACKUP'} alive={state.primaryAlive}/><div className="repLine"><span>SYNC</span><i></i><i></i><i></i></div><NodeCard node="NODE-2" role={state.activePrimary==='NODE-2'?'PRIMARY':'BACKUP'} alive={state.backupAlive}/></div></section>
 <div className="metrics"><Metric label="Payment volume" value={money(volume)} sub={`${payments.length} transactions`}/><Metric label="Successful" value={success} sub="captured payment events"/><Metric label="Replication" value={cons.consistent?'CONSISTENT':'DRIFT'} sub={`${cons.primaryCount||0} primary / ${cons.backupCount||0} backup`}/><Metric label="Lamport clock" value={state.lamport||0} sub="logical event time"/></div>
 <section className="grid2"><div className="panel"><PanelTitle icon={<ShieldCheck/>} title="Resilience status" action="Experiment 5"/><div className="statusRows"><StatusRow label="Primary node" value={state.primaryAlive?'HEALTHY':'FAILED'} ok={state.primaryAlive}/><StatusRow label="Backup node" value={state.backupAlive?'HEALTHY':'FAILED'} ok={state.backupAlive}/><StatusRow label="Replication link" value={state.replicationEnabled?'SYNCHRONOUS':'DROPPED'} ok={state.replicationEnabled}/><StatusRow label="Coordinator" value={state.coordinator||'—'} ok={true}/></div></div><div className="panel"><PanelTitle icon={<GitBranch/>} title="Distributed control"/><div className="controlGrid"><Control label="Fail primary" on={()=>action('FAIL_PRIMARY')} disabled={busy}/><Control label="Elect coordinator" on={()=>action('START_ELECTION')} disabled={busy}/><Control label="Promote backup" on={()=>action('PROMOTE_BACKUP')} disabled={busy}/><Control label="Resync" on={()=>action('RESTORE_REPLICATION')} disabled={busy}/></div></div></section>
 <section className="panel"><PanelTitle icon={<Activity/>} title="Recent payment events" action="Live"/><PaymentTable rows={payments.slice(0,6)}/></section>
 </>}
function NodeCard({node,role,alive}:any){return <div className={'nodeCard '+(!alive?'down':'')}><div className="nodeTop"><Server size={17}/><span>{node}</span><b>{alive?'●':'×'}</b></div><strong>{role}</strong><small>{alive?'Ready to process':'Failure injected'}</small></div>}
function Metric({label,value,sub}:any){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function PanelTitle({icon,title,action}:any){return <div className="panelTitle"><span className="panelIcon">{icon}</span><h3>{title}</h3>{action&&<span className="panelAction">{action}</span>}</div>}
function StatusRow({label,value,ok}:any){return <div className="statusRow"><span>{label}</span><b className={ok?'ok':'bad'}>{ok?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>} {value}</b></div>}
function Control({label,on,disabled}:any){return <button className="control" onClick={on} disabled={disabled}>{label}<ChevronRight size={14}/></button>}

function Payments({payments,amount,setAmount,method,setMethod,processor,setProcessor,idem,setIdem,create}:any){return <><section className="panel formPanel"><PanelTitle icon={<Banknote/>} title="Create payment" action="Real backend transaction"/><div className="formGrid"><label>Amount (INR)<input value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="UPI">UPI</option><option value="CARD">Card</option><option value="NETBANKING">Net Banking</option></select></label><label>Processor override<select value={processor} onChange={e=>setProcessor(e.target.value)}><option value="">Smart route</option><option>UPI-Processor</option><option>Card-Processor</option><option>Banking-Processor</option></select></label><label>Idempotency key<input placeholder="Auto-generated if blank" value={idem} onChange={e=>setIdem(e.target.value)}/></label></div><button className="primaryBtn" onClick={create}>Process payment <ArrowRight size={16}/></button></section><section className="panel"><PanelTitle icon={<Activity/>} title="Payment ledger" action={`${payments.length} shown`}/><PaymentTable rows={payments}/></section></>}
function PaymentTable({rows}:any){return <div className="tableWrap"><table><thead><tr><th>Payment</th><th>Amount</th><th>Method</th><th>Processor</th><th>Status</th><th>Node</th><th>Lamport</th></tr></thead><tbody>{rows.length?rows.map((p:any)=><tr key={p.payment_id}><td><b>{p.payment_id}</b><small>{p.order_id}</small></td><td>{money(p.amount)}</td><td>{p.method}</td><td>{p.processor_id||'—'}</td><td><span className={'status '+(p.status==='SUCCESS'?'success':'pending')}>{p.status}</span></td><td>{p.primary_node_id}</td><td>{p.lamport_ts}</td></tr>):<tr><td colSpan={7} className="empty">No payments yet.</td></tr>}</tbody></table></div>}

function Experiment({state,cons,payments,action,busy,runDemo}:any){return <><section className="experimentHero"><div><span className="tag">LIVE LAB / FAULT TOLERANCE</span><h2>Primary → Backup → Election → Recovery</h2><p>The demo makes the distributed state transition visible. Synchronous replication means the backup acknowledgement is part of the commit path.</p></div><button className="primaryBtn" onClick={runDemo} disabled={busy}><Play size={16}/> Run complete scenario</button></section><section className="stepper"><Step n="01" title="Normal operation" text="NODE-1 primary" done={state.primaryAlive&&state.activePrimary==='NODE-1'}/><Step n="02" title="Inject failure" text="Heartbeat timeout" done={!state.primaryAlive}/><Step n="03" title="Bully election" text="NODE-2 wins" done={state.coordinator==='NODE-2'}/><Step n="04" title="Failover payment" text="New primary accepts" done={state.activePrimary==='NODE-2'}/><Step n="05" title="Resync" text="Consistency = 0 mismatch" done={cons.consistent}/></section><div className="grid2"><div className="panel"><PanelTitle icon={<Server/>} title="Node state"/><div className="nodeLarge"><NodeCard node="NODE-1" role={state.activePrimary==='NODE-1'?'PRIMARY':'FORMER PRIMARY'} alive={state.primaryAlive}/><NodeCard node="NODE-2" role={state.activePrimary==='NODE-2'?'PRIMARY':'BACKUP'} alive={state.backupAlive}/></div></div><div className="panel"><PanelTitle icon={<ShieldCheck/>} title="Consistency proof"/><div className="proof"><div><span>Primary records</span><strong>{cons.primaryCount||0}</strong></div><div><span>Backup records</span><strong>{cons.backupCount||0}</strong></div><div><span>Field mismatches</span><strong className={cons.mismatches?'badText':'goodText'}>{cons.mismatches||0}</strong></div><div className="proofResult">{cons.consistent?<><CheckCircle2/> DATA IS CONSISTENT</>:<><AlertTriangle/> REPLICATION DRIFT</>}</div></div></div></div><section className="panel"><PanelTitle icon={<Activity/>} title="Failure injection controls"/><div className="controlGrid big"><Control label="Fail NODE-1" on={()=>action('FAIL_PRIMARY')} disabled={busy}/><Control label="Recover NODE-1" on={()=>action('RECOVER_PRIMARY')} disabled={busy}/><Control label="Start Bully election" on={()=>action('START_ELECTION')} disabled={busy}/><Control label="Promote NODE-2" on={()=>action('PROMOTE_BACKUP')} disabled={busy}/><Control label="Drop replication" on={()=>action('DROP_REPLICATION')} disabled={busy}/><Control label="Set synchronous" on={()=>action('SET_SYNC')} disabled={busy}/><Control label="Set asynchronous" on={()=>action('SET_ASYNC')} disabled={busy}/><Control label="Restore + resync" on={()=>action('RESTORE_REPLICATION')} disabled={busy}/><Control label="Fail backup" on={()=>action('FAIL_BACKUP')} disabled={busy}/><Control label="Reset lab" on={()=>action('RESET')} disabled={busy}/></div></section></>}
function Step({n,title,text,done}:any){return <div className={'step '+(done?'done':'')}><span>{done?<CheckCircle2/>:n}</span><b>{title}</b><small>{text}</small></div>}
function Nodes({state,action,election}:any){const nodes=[state.primaryNode,state.backupNode].filter(Boolean);const terminals=election.terminals||[{id:'T1',priority:10,alive:true},{id:'T2',priority:25,alive:true},{id:'T3',priority:40,alive:true},{id:'T4',priority:15,alive:true},{id:'T5',priority:30,alive:true}];return <><section className="panel"><PanelTitle icon={<GitBranch/>} title="Bully election topology" action="Priority-based / 5 terminals"/><div className="bully">{terminals.map((t:any)=><div className={'terminal '+(t.id===election.coordinator?'active':'')+(t.alive?'':' downTerminal')} key={t.id}>{t.id}<small>priority {t.priority}</small><b>{t.alive?(t.id===election.coordinator?'COORDINATOR':'ACTIVE'):'FAILED'}</b></div>)}</div><p className="note">Academic election layer: T1=10, T2=25, T3=40, T4=15, T5=30. With all terminals alive, T3 coordinates; after T3 fails, T5 is the highest-priority active terminal. The payment gateway's NODE-1/NODE-2 primary-backup layer is kept separate from these five educational election terminals.</p><button className="primaryBtn" onClick={()=>action('START_ELECTION')}>Start Bully election <ArrowRight size={16}/></button></section><div className="metrics"><Metric label="Election coordinator" value={election.coordinator||'—'} sub={`election #${election.elections||0}`}/><Metric label="Gateway primary" value={state.activePrimary||'—'} sub="payment data plane"/><Metric label="NODE-1" value={state.primaryAlive?'UP':'DOWN'} sub="gateway priority 40"/><Metric label="NODE-2" value={state.backupAlive?'UP':'DOWN'} sub="gateway priority 30"/></div><section className="panel"><PanelTitle icon={<Server/>} title="Payment nodes"/><div className="nodeTable">{nodes.map((n:any)=><div className="nodeLine" key={n.id}><Server/><b>{n.id}</b><span>{n.role}</span><span>{n.priority} priority</span><strong className={n.status==='UP'?'goodText':'badText'}>{n.status}</strong></div>)}</div></section></>}
function Clock({clock,setClock,action}:any){return <><section className="panel"><PanelTitle icon={<Clock3/>} title="Berkeley + Lamport lab" action="Physical + logical time"/><p className="note">Berkeley reduces clock-offset differences; Lamport timestamps provide logical event ordering. They solve different problems and are recorded separately.</p><button className="primaryBtn" onClick={async()=>setClock(await api('/clock-sync'))}>Run Berkeley synchronization <ArrowRight size={16}/></button>{clock.nodes&&<div className="clockTable">{clock.nodes.map((n:any)=><div className="clockRow" key={n.node}><b>{n.node}</b><span>offset {n.offset>=0?'+':''}{n.offset}s</span><span>target {clock.targetOffset}s</span><strong>{clock.targetOffset-n.offset>=0?'+':''}{clock.targetOffset-n.offset}s</strong></div>)}</div>}</section><section className="panel"><PanelTitle icon={<Activity/>} title="Lamport lifecycle"/><div className="timeline"><div>Payment Created <b>L=1</b></div><ArrowRight/><div>Smart Routing <b>L=2</b></div><ArrowRight/><div>Payment Attempt <b>L=3</b></div><ArrowRight/><div>Payment Completed <b>L=4</b></div></div></section></>}
function Ledger({ledger,settlement,action}:any){return <><div className="metrics"><Metric label="Ledger verification" value={ledger.balanced?'BALANCED':'DRIFT'} sub={`${ledger.unbalancedTransactions||0} unbalanced transactions`}/><Metric label="Gross volume" value={money(settlement.gross)} sub="successful payments"/><Metric label="Fees" value={money(settlement.fees)} sub="demo 2% fee model"/><Metric label="Net settlement" value={money(settlement.net)} sub="ready for payout"/></div><section className="panel"><PanelTitle icon={<Database/>} title="Double-entry verification"/><div className="proofResult large">{ledger.balanced?<><CheckCircle2/> Every transaction balances: debit = credit</>:<><AlertTriangle/> Unbalanced transactions detected</>}</div></section><section className="panel"><PanelTitle icon={<Banknote/>} title="Settlement pipeline"/><div className="timeline"><div>Capture <b>SUCCESS</b></div><ArrowRight/><div>Settlement cycle <b>READY</b></div><ArrowRight/><div>Netting <b>2% fee</b></div><ArrowRight/><div>Payout <b>READY</b></div></div><button className="primaryBtn" onClick={()=>action('RESYNC')}>Re-run consistency check <RefreshCw size={16}/></button></section></>}
function Logs({events}:any){return <section className="panel"><PanelTitle icon={<Activity/>} title="Distributed system event log" action="Lamport ordered"/><div className="logs">{events.length?events.map((e:any)=><div className="log" key={e.event_id}><span>L{e.lamport_ts}</span><b>{e.event_type}</b><p>{e.message}</p><small>{String(e.created_at||'')}</small></div>):<div className="empty">No events yet.</div>}</div></section>}

createRoot(document.getElementById('root')!).render(<App/>);
