spring.application.name=paymesh-backend
server.port=${PAYMESH_NODE_PORT:8080}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/dc_paygateway?allowMultiQueries=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jackson.serialization.write-dates-as-timestamps=false
spring.sql.init.mode=never
paymesh.node-id=${PAYMESH_NODE_ID:NODE-1}
